name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 更新到 v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4 # 更新到 v4
        with:
          node-version: 14.21.3
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn' # 开启 yarn 缓存，减少 install 时间

      - name: Install
        # 设置 python3 路径，解决 node-gyp 寻找 python2 的问题
        run: |
          yarn config set python python3
          yarn install --frozen-lockfile
        env:
          PYTHON: python3

      - name: Release
        run: |
          # 确保在发布前代码状态是干净的
          git checkout .
          # 使用 lerna 发布
          yarn lerna publish from-package --force-publish --no-git-tag-version --no-push --yes --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYTHON: python3